### ISSUE TITLE
Making input position available to values returned by parsers

### ISSUE THREAD

**Issue by arseniiv** [drhagen/parsita#11]
Hi! In Sprache C# library, there is a tool to make a position at which the value vas parsed, available to it, [as a parser wrapper](https://github.com/sprache/Sprache/blob/master/src/Sprache/Parse.Positioned.cs). The same could be done here: if there’s a method, say, `set_pos(start, length)`, it would be called by the primitive `positioned` (or something) on a succesful parse.

What do you think about it?

**Comment by drhagen** [comment]
This is an interesting and useful feature. It is straightforward to implement with Parsita. Below is one possible implementation and an example usage.

```python
from abc import abstractmethod
from typing import Generic

from parsita import Parser
from parsita.state import Reader, Status, Continue, Input, Output


class PositionAware(Generic[Output]):
    @abstractmethod
    def set_position(self, start: int, length: int) -> Output:
        pass


class PositionedParser(Generic[Input, Output], Parser[Input, Output]):
    def __init__(self, parser: Parser[Input, PositionAware[Output]]):
        super().__init__()
        self.parser = parser

    def consume(self, reader: Reader[Input]) -> Status[Input, Output]:
        start = reader.position
        status = self.parser.consume(reader)

        if isinstance(status, Continue):
            end = status.remainder.position
            return Continue(status.remainder, status.value.set_position(start, end - start)).merge(status)
        else:
            return status

    def __repr__(self):
        return self.name_or_nothing() + 'positioned({})'.format(self.parser.name_or_repr())


positioned = PositionedParser

if __name__ == '__main__':
    from dataclasses import dataclass
    from parsita import TextParsers, reg
    from parsita.util import splat

    @dataclass
    class UnfinishedVariable(PositionAware):
        name: str

        def set_position(self, start: int, length: int):
            return Variable(self.name, start, length)

    @dataclass
    class Variable:
        name: str
        start: int
        length: int

    @dataclass
    class Plus:
        first: Variable
        second: Variable

    class PlusParsers(TextParsers):
        variable = positioned(reg('[A-Za-z][A-Za-z0-9_]*') > UnfinishedVariable)
        plus = variable & '+' >> variable > splat(Plus)

    print(PlusParsers.plus.parse('abc + xyz').or_die())
```

I am undecided if this is appropriate to add as a standard parser in Parsita. This is a bit more narrowly focused than the current built-in parsers. I am not sure if Sprache makes it easy for the user to add new parsers, but Parsita makes it fairly straightforward to do so. I am also not confident that this is the appropriate API for Python. Would this be more useful if all parsers called `set_position` if `status.value` was an instance of `PositionAware` or for which `hasattr('set_position')` was true? Would that be better confined to a feature of a particular flag on the `GeneralParsers` context class?

Right now, I am inclined to make this one of Parsita's examples (for a user being able to define his own `Parser` subclass). If the example sees enough usage to make me confident that the design is right, I'll promote it into the standard parsers' list.

**Comment by arseniiv** [comment]
Thank you! :smile: 

> I am also not confident that this is the appropriate API for Python. Would this be more useful if all parsers called `set_position` if `status.value` was an instance of `PositionAware` or for which `hasattr('set_position')` was true?

Oh, I didn’t think about that, it seems to be better indeed, as when the value has `set_position`, it usually needs to be called when it may be. OTOH inclusions of `positioned` can document precise places in the code the position is recorded, though I don’t know if it’s a useful thing or not.
