### ISSUE TITLE
Alternate Parser example does not work

### ISSUE THREAD

**Issue by JosephCottam** [drhagen/parsita#12]
Copying from the examples:

```
from parsita import *
class NumberParsers(TextParsers):
    integer = reg(r'[-+]?[0-9]+') > int
    real = reg(r'[+-]?\d+\.\d+(e[+-]?\d+)?') | 'nan' | 'inf' > float
    number = integer | real
    
assert NumberParsers.number.parse('4.0000') == Success(4.0)
```

Fails with error:
```
AssertionError                            Traceback (most recent call last)
<ipython-input-3-e8cd6909f576> in <module>
      6     number = integer | real
      7 
----> 8 assert NumberParsers.number.parse('4.0000') == Success(4.0)
```

Switching   `number = real | integer`  works as advertised.

I'm running python 3.7.4 and parsita 1.3.2 on Mac OS 10.13.6.

**Comment by drhagen** [comment]
Confirmed. Thanks for the report. The example contains a common mistake where the first alternative can match the start of the second alternative, causing the parser to lock in that match and never get to the later alternative. I'll fix the example now and plan to either add an additional example detailing this pitfall (that even I fell into) or add the ability to do full backtracking in the alternative parser.
