### ISSUE TITLE
A slight mismatch in `Parser` doc

### ISSUE THREAD

**Issue by arseniiv** [drhagen/parsita#13]
Hi again! `Parser`’s doc states:
```
2. Implement the ``__str__`` method
```
but what is actually needed and implemented in subclasses is the `__repr__` method. :slightly_smiling_face:

**Comment by drhagen** [comment]
You are correct. I'll update the docs. I think I am using `__repr__` inappropriately anyway. I should probably change all the definitions of `__repr__` into definitions of `__str__`.
