### ISSUE TITLE
Documentation doesn't cover how to use the results

### ISSUE THREAD

**Issue by nathanielvirgo** [drhagen/parsita#19]
The tutorial is great, but I can't find any other documentation, and it seems the tutorial neglects to mention how to actually get the result from parsing something. If I have an object like `Success("hello")`, how can I get the string "hello" out of that object in my code? The examples only ever print the success object or assert that it has the correct value.

**Comment by nathanielvirgo** [comment]
Ugh, I was calling `dir()` on the wrong object. Now I see that there is a `value` method that returns the contents.

However, it still seems odd that the documentation doesn't mention this. It would be nice to have an example of checking that parsing was successful and returning the results if so.

**Comment by drhagenabm** [comment]
That is actually good point. I don't mention how to get the value out at all in the tutorial. The Python help is up-to-date (i.e. `help(Success)`), but I know that most people expect that to be put on the web with Sphinx and readthedocs or something.

**Comment by drhagen** [comment]
That is actually good point. I don't mention how to get the value out at all in the tutorial. The Python help is up-to-date (i.e. `help(Success)`), but I know that most people expect that to be put on the web with Sphinx and readthedocs or something.

**Comment by drhagen** [comment]
Oh, and to answer your question, you test if `result` is `Success` or `Failure` using `isinstance(result, Success)`. That always seemed like the cleanest solution you can get in Python, at least until [PEP-634](https://www.python.org/dev/peps/pep-0634/) gets implemented. Alternatively, you can call `result.or_die()` to return the value if `Success` and raise an `ParseError` exception if `Failure`.

**Comment by nathanielvirgo** [comment]
Aah, I don't know why it didn't occur to me to use the Python help. Thanks so much for the quick response!
