### ISSUE TITLE
Contribution question

### ISSUE THREAD

**Issue by lostinplace** [drhagen/parsita#27]
Hi there!

Unbeknownst to you, I've been using your library for what feels like a long time now.  (Congratulations, your code is part of the enormous system that drives Alexa!)

I was talking to a colleague about your library, and part of the discussion includes, "I've got a bunch of parsers that are important, but aren't part of the library."  The colleague asked, "why haven't you submitted them back?"  and my answer was pretty unsatisfying (to me at least): "I don't know if he's looking for contributions like this."

So I'm explicitly asking the question:  I've got some additional parsers that are pretty useful when working with the library, would you like me to submit a full package? (including documentation)

Here's a brief rundown of what I'm talking about:

```python

def excluding(parser: Parser[Input, Output]) -> ExcludingParser:
    """Match anything unless it matches the provided parser

    This matches all text until text that is matched by the provided parser is encountered.

    Args:
        :param parser: a parser that parses terms that you don't want to capture
    """
    if isinstance(parser, str):
        parser = lit(parser)
    return ExcludingParser(parser)


def at_least(n: int, parser: [Input, Output]) -> RepeatedAtLeastNParser:
    """Match a parser at least n times

    This matches ``parser`` multiple times in a row. If it matches as least
    n times, it returns a list of values that represents each time ``parser`` matched. If it
    matches ``parser`` less than n times it fails.

    Args:
        :param parser: Parser or literal
        :param n: count of minimum matches
    """
    if isinstance(parser, str):
        parser = lit(parser)
    return RepeatedAtLeastNParser(n, parser)


def check(parser: Parser[Input, Output]) -> ExcludingParser:
    """Evaluates to see if you're on the right track without consuming input

    This will match text against the provided parser, and continue if that parser can move forward, else it will backtrack

    Args:
        :param parser: a parser that parses terms that you want to make sure are present
    """
    if isinstance(parser, str):
        parser = lit(parser)
    return CheckParser(parser)

def debug(
        parser: Parser[Input, Output], verbose: bool = False,
        callback: Callable[[Parser[Input, Input], Reader[Input]], None]  = None
) -> DebugParser:
    """Lets you set breakpoints and print parser progress

    You can use the verbose flag to print messages as the parser is being evaluated

    You can use the callback method to insert a callback that will execute before the parser is evaluated, the call will include the reader

    Args:
        :param parser: a parser that parses terms that you want to make sure are present
        :param verbose: write progress messages to stdout
        :param callback: calls this function before evaluating the provided parser
    """
    if isinstance(parser, str):
        parser = lit(parser)
    return DebugParser(parser, verbose, callback)


# note, I think you've already produced a "longest" parser that replicates this, in the latest version
def best(*parsers: Parser[Input, Output]) -> BestAlternativeParser:
    """Will return the furthest progress from any list of parsers

    This will try each parser provided, and return the result of the one that made it the farthest

    Args:
        :param parsers: a list of parsers or a single AlternativeParser

    """
    processed_parsers = []
    for parser in parsers:
        if isinstance(parser, str):
            processed_parsers.append(lit(parser))
        else:
            processed_parsers.append(parser)
    first_parser = processed_parsers[0]
    if len(processed_parsers) == 1 and isinstance(first_parser, AlternativeParser):
        processed_parsers = first_parser.parsers
    return BestAlternativeParser(*processed_parsers)


def track(parser: Parser[Input, Output]) -> ExcludingParser:
    """Tracks the current depth of the start of the successful parser

    This will match text against the provided parser, and accept if that parser can move forward, else it will backtrack.
    the result it returns will include an integer that specifies the depth that the match began

    Args:
        :param parser: a parser that parses terms that you want to make sure are present
    """
    if isinstance(parser, str):
        parser = lit(parser)
    return TrackParser(parser)

# Note: This might be better implemented as a flag on repsep
def repwksep(
    parser: Union[Parser, Sequence[Input]], separator: Union[Parser, Sequence[Input]]
) -> RepeatWithKeptSeparatorsParser:
    """Match a parser zero or more times separated by another parser, and keeps the separators.

    This matches repeated sequences of ``parser`` separated by ``separator``. A
    list is returned containing tuples of matched values and separators If there are no matches, an empty
    list is returned.

    Args:
        parser: Parser or literal
        separator: Parser or literal
    """
    if isinstance(parser, str):
        parser = lit(parser)
    if isinstance(separator, str):
        separator = lit(separator)
    return RepeatWithKeptSeparatorsParser(parser, separator)


def tag(
    parser: Parser, tag_contents: str
) -> TagParser:
    """
    Prepends the output of the provided parser with static content
    
    Useful for identifying which parser was successful.
    
    :param parser: 
    :param tag_contents: the result that should be prepended to the output stream 
    :return: 
    """

def msg(
    parser: Parser, message_contents: str
) -> MessageParser:
    """
    Replace the name of the provided parser

    Useful for controlling the output messages of failed parsers

    :param parser:
    :param message_contents:
    :return:
    """

```

**Comment by drhagen** [comment]
I am definitely looking for contributions like this. You are right that some of these have been superseded by recent features or would be better as optional arguments to existing parsers. But some of them are definitely unique and should be added. I'll think longer about this list weekend and provide a preliminary judgement. Feel free to open a PR in the meantime if you are ok with me ultimately cutting some of them in the end.

**Comment by drhagen** [comment]
Here are my thoughts on each of the parsers. Overall, most of there are features that would be great additions to Parsita.

- `excluding`: This is a very interesting combinator. How much input does this consume? What does this return? Is this just negative lookahead?
- `at_least`: This should probably be a keyword argument to `rep` (with the same thing added to `repsep`). I am not sure about the name of the keyword argument. I am inclined toward `min`, but `at_least` might work. Whatever we choose, I want it to be forwards compatible with adding an upperbound, should anyone need that, so `n` is right out.
  - `rep(parser: Parser, *, min: int = 0)`
  - `repsep(parser: Parser, separator: Parser, *, min: int = 0)`
- `check`: This is what is commonly called lookahead, right? I would probably rename this to `lookahead` because I did not find the name `check` to be that intuitive.
- `debug`: I like this. It should be added as is.
- `best`: This looks to definitely be the same thing as `longest`. We won't a new implementation, but I _really_ like the name `best` over `longest`, and am genuinely considering renaming `longest` (with deprecation).
- `track`: This is an intriguing combinator that I would like to learn more about. Is it mainly for debugging?
- `repwksep`: Does this return the separators inline like `['2', '+', '2', '-', '1']` or in some other structure? If inline, then I agree that a keyword argument (probably `drop_separator`) is the way to go.
  - `repsep(parser: Parser, separator: Parser, *, drop_separator: bool = True)`
  - `rep1sep(parser: Parser, separator: Parser, *, drop_separator: bool = True)`
- `tag`: This one I am inclined to leave out. It seems pretty specific and the conversion parser ` > ` can do it more generally.
- `msg`: How does this work? Because the message does not exist until parsing is done. Does this replace `expected`?

**Comment by lostinplace** [comment]
going down the list:

`excluding`:  this is "consume until the provided parser starts succeeding". let's imagine a block of text:

```
Ambiguous Content:

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

:End Ambiguous Content
```

If I want to parse this block without the `excluding` parser, I need to normalize and parse the "Ambiguous Content".  With excluding:

```python

class BlockParser(TextParsers):
    ambigous_block_start = lit('Ambiguous Content:')
    ambigous_block_end = lit(':End Ambiguous Content')
    ambiguous_conent = not(ambigous_block_end)
    ambiguous block = ambigous_block_start >> ambiguous_conent << ambigous_block_end

```

Originally I had a `bound` parser, that allowed you to specify the start and end, parser inline, (e.g. `bound(ambigous_block_start, ambigous_block_end)`. but I end up having a whole bunch of parsers that had `bound(any, some_end)` so I broke it up

**Comment by drhagen** [comment]
Now that documentation has been added covering the parsers added in #28 and #29, this is done. If anyone wants to argue for one of the unimplemented combinators, please open a new ticket and link to this one.
